### ISSUE TITLE
Unable to compile on centos7

### ISSUE THREAD

**Issue by willDTF** [boberfly/GafferDenoise#1]
Hello, 
i'm not able to compile it on centos 7
by default, the 'cmake'c comment use cmake2 so I've updated the config.py with 'cmake3' line 22 & 30 and I have an error with oind folder, even if it exist 
![image](https://user-images.githubusercontent.com/4272733/132700776-7b063d7c-1698-4a0a-a8b8-71480030f0a9.png)

here is the terminal:

`[william@hawkins dependencies]$ build/build.py --project OpenImageDenoise --buildDir $GAFFERDENOISE_INSTALL_PREFIX --gafferRoot $GAFFER_ROOT --buildType release
mkdir gafferBuild
cd gafferBuild && cmake3 -G "Unix Makefiles" -D CMAKE_CXX_COMPILER=g++ -D CMAKE_INSTALL_PREFIX=/home/william/Downloads/GafferDenoise-main -D CMAKE_PREFIX_PATH=/opt/gaffer-0.60.6.0-linux-python2 -D CMAKE_BUILD_TYPE=release -D OIDN_STATIC_LIB=ON ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/g++
-- Check for working CXX compiler: /bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /opt/gaffer-0.60.6.0-linux-python2/bin/python (found version "2.7.15") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for TBB components tbb; ()
-- Found TBB version 2018.0 at /opt/gaffer-0.60.6.0-linux-python2
-- Performing Test compiler-openmp-simd-support
-- Performing Test compiler-openmp-simd-support - Failed
********************************************
Could not find ISPC (looked in PATH and /home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.16.0-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.16.0-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.16.0-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.16.0-Linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.16.0-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.16.0-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.16.0-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.16.0-Linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.15.0-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.15.0-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.15.0-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.15.0-Linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.15.0-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.15.0-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.15.0-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.15.0-Linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.14.1-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.14.1-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.14.1-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-1.14.1-Linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.14.1-linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.14.1-linux/bin;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.14.1-Linux;/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../ispc-v1.14.1-Linux/bin)

This version of Intel(R) Open Image Denoise expects you to have a binary install of ISPC minimum version 1.14.1, and expects it to be found in 'PATH' or in the sibling directory to where the Intel Open Image Denoise sources are located. Please go to https://ispc.github.io/downloads.html, select the binary release for your particular platform, and unpack it to /home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/../

If you insist on using your own custom install of ISPC, please make sure that the 'ISPC_EXECUTABLE' variable is properly set in CMake.
********************************************
CMake Error at cmake/oidn_ispc.cmake:41 (message):
  Could not find ISPC.  Exiting.
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)

-- Configuring incomplete, errors occurred!
See also "/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/gafferBuild/CMakeFiles/CMakeOutput.log".
See also "/home/william/Downloads/GafferDenoise-main/dependencies/OpenImageDenoise/working/oidn-1.4.1/gafferBuild/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "build/build.py", line 257, in <module>
    __buildProject( args.project, args.gafferRoot, args.buildDir, args.buildType, args.forceLibLinkType, args.forceCCompiler, args.forceCxxCompiler )
  File "build/build.py", line 203, in __buildProject
    subprocess.check_call( command, shell = True, env = environment )
  File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd gafferBuild && cmake3 -G "Unix Makefiles" -D CMAKE_CXX_COMPILER=g++ -D CMAKE_INSTALL_PREFIX=/home/william/Downloads/GafferDenoise-main -D CMAKE_PREFIX_PATH=/opt/gaffer-0.60.6.0-linux-python2 -D CMAKE_BUILD_TYPE=release -D OIDN_STATIC_LIB=ON ..' returned non-zero exit status 1`

thank you

**Comment by boberfly** [comment]
Hey @Kaiz3rTool you need ISPC installed and somewhere it can find it.

Cheers

**Comment by willDTF** [comment]
hi, sorry I missed it... 
building ISPC is quite complex so I guess I will wait a centos release to test it
thanks

**Comment by boberfly** [comment]
@Kaiz3rTool you can just download the compiler eg.
https://github.com/ispc/ispc/releases/download/v1.16.1/ispc-v1.16.1-linux.tar.gz
No need to compile it.

**Comment by willDTF** [comment]
Thanks for the link

I have tried with it but I'm still not able to complete it, with the following feedback : 

[CMakeOutput.log](https://github.com/boberfly/GafferDenoise/files/7277301/CMakeOutput.log)

`gmake: *** [all] Error 2
Traceback (most recent call last):
  File "build/build.py", line 257, in <module>
    __buildProject( args.project, args.gafferRoot, args.buildDir, args.buildType, args.forceLibLinkType, args.forceCCompiler, args.forceCxxCompiler )
  File "build/build.py", line 203, in __buildProject
    subprocess.check_call( command, shell = True, env = environment )
  File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd gafferBuild && cmake3 --build . --config release --target install -- -j 80' returned non-zero exit status 2
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:15 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /opt/gaffer-0.60.6.0-linux-python3

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" (requested
  version 2017.0) with any of the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/william/Documents/SCRIPTS/GafferDenoise/cmake-build-default/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `install'.  Stop.`
